name: Deploy to FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ftp-deploy:
    name: Sync Files to Server via FTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Deploy to Web Server via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT || 21 }}
          protocol: ${{ secrets.FTP_PROTOCOL || 'ftp' }}
          server-dir: ${{ secrets.FTP_SERVER_DIR || 'public_html/wp-content/plugins/my-booking-engine/' }}
          exclude: |
            **/.git*
            **/.git*/**
            **/.github*
            **/.github*/**
            README.md
            *.zip
            .gitignore
            composer.json
            composer.lock
            package.json
            package-lock.json
            node_modules/**
